### ISSUE TITLE
pip install fastfix does not work

### ISSUE THREAD

**Issue by vikram223** [elec-otago/fastfix#7]
We get following issue in the default installation with Anaconda Python 3.8 environment
(base) C:\WINDOWS\system32>pip3 install fastfix
Collecting fastfix
  Using cached fastfix-0.1.0b3.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\<user>\AppData\Local\Temp\pip-install-1zbuka4t\fastfix_9ce2da92be5045ca9c97e8e33ea59821\setup.py", line 10, in <module>
          readme = f.read()
        File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2980: character maps to <undefined>
      [end of output]

issue can be fixed by modifying setup.py line 10 as below
with open('README.md') as f:
to
with open('README.md','r',encoding="utf-8") as f:

**Comment by tmolteno** [comment]
Thanks for the feedback. I'll make the change as you request.
